# SPDX-License-Identifier: Apache-2.0
name: "Delete automation Latitude Namespaces"
permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "0 23 * * *"
    # at 6pm Central Time
  workflow_dispatch:
    inputs:
      Dallas_n1:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n1 (Daily SDPT/SDLT)"

      Dallas_n2:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n2 (Daily SDPT/SDLT)"

      Dallas_n3:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n3 (weekly runs)"

      Dallas_n4:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n4 (weekly runs)"

      Chicago_n5:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n5 (branch testing)"

      Chicago_n6:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n6 (branch testing)"

      Chicago_n7:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n7 (branch testing)"

      Chicago_n8:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n8 (SDPT/SDLT)"

      Chicago_n9:
        type: boolean
        required: false
        default: false
        description: "solo-sd*t-n9 (SDPT/SDLT)"

jobs:
  delete-selected-namespaces:
    runs-on: hiero-citr-linux-small
    env:
      Dallas_n1: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.Dallas_n1 }}
      Dallas_n2: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.Dallas_n2 }}
      Dallas_n3: ${{ github.event.inputs.Dallas_n3 }}
      Dallas_n4: ${{ github.event.inputs.Dallas_n4 }}
      Chicago_n5: ${{ github.event.inputs.Chicago_n5 }}
      Chicago_n6: ${{ github.event.inputs.Chicago_n6 }}
      Chicago_n7: ${{ github.event.inputs.Chicago_n7 }}
      Chicago_n8: ${{ github.event.inputs.Chicago_n8 }}
      Chicago_n9: ${{ github.event.inputs.Chicago_n9 }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install KubeCtl
        uses: step-security/setup-kubectl@2edbf6aff97d814e9dc52827498ac51fe972e6d0 # v4.0.0

      - name: Install Teleport Client
        uses: teleport-actions/setup@176c25dfcd19cd31a252f275d579822b243e7b9c # v1.0.6
        with:
          version: 18.1.4

      - name: Authorize Teleport SSH Access
        id: auth-ssh
        uses: teleport-actions/auth@685adaf480dc79262a99220eb158a92136d5abd9 # v2.0.3
        with:
          proxy: hashgraph.teleport.sh:443
          token: gh-citr-performance-svcs-bot

      - name: Authorize Teleport K8S Access to Dallas Cluster
        id: auth-k8s-dal
        uses: teleport-actions/auth-k8s@677da98eaa78a5e649d4c5b4012750af4c28af73 # v2.0.3
        with:
          proxy: hashgraph.teleport.sh:443
          token: gh-citr-performance-svcs-bot
          kubernetes-cluster: k8s.pft.dal.lat.ope.eng.hashgraph.io
          certificate-ttl: 20h

      - name: Dallas Latitude namespaces
        run: |
          set +e
          set +x
          clusterZone="Dallas"
          for namespace in `sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces | awk '{print $1}' | grep -E 'solo[\-].*[\-]n[1-9]'`
          do
            n="$(echo "${namespace}" | perl -ne 'print "$1\n" if /^solo\-.*d.*t\-n(\d+)$/')"
            env | grep ${clusterZone}_n${n}
            isChecked=$(env | grep ${clusterZone}_n${n} | awk -F= '{print $NF}')
            if [ "${isChecked}" = "true" ]
            then
              echo "Deleting ${namespace}"
              sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt delete namespace ${namespace}
            fi
          done
          exit 0

      - name: Authorize Teleport K8S Access to Chicago Cluster
        id: auth-k8s-chi
        uses: teleport-actions/auth-k8s@677da98eaa78a5e649d4c5b4012750af4c28af73 # v2.0.3
        with:
          proxy: hashgraph.teleport.sh:443
          token: gh-citr-performance-svcs-bot
          kubernetes-cluster: k8s.pft.chi.lat.ope.eng.hashgraph.io
          certificate-ttl: 20h

      - name: Chicago Latitude namespaces
        run: |
          set +e
          set +x
          clusterZone="Chicago"
          for namespace in `sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces | awk '{print $1}' | grep -E 'solo[\-].*[\-]n[1-9]'`
          do
            n="$(echo "${namespace}" | perl -ne 'print "$1\n" if /^solo\-.*d.*t\-n(\d+)$/')"
            env | grep ${clusterZone}_n${n}
            isChecked=$(env | grep ${clusterZone}_n${n} | awk -F= '{print $NF}')
            if [ "${isChecked}" = "true" ]
            then
              echo "Deleting ${namespace}"
              sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt delete namespace ${namespace}
            fi
          done
          exit 0
